# Use root/example as user/password credentials
version: '3'

services:
  db:
    image: mariadb
    container_name: db
    restart: always
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: backend
      MYSQL_USER: backend
      MYSQL_PASSWORD: changeme
    networks:
      - backend-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - backend-network
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./php:/php
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - backend-network
  php:
    image: payano/php-fpm-mysql
    volumes:
        - ./php:/php
    networks:
      - backend-network
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001    
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
