# Use root/example as user/password credentials
version: '3'

services:
  db:
    image: mariadb
    container_name: db
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./mysql_script/backend.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: backend
      MYSQL_USER: backend
      MYSQL_PASSWORD: changeme
    networks:
      - backend-network
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: pma
    environment:
      - PUID=1000
      - PGID=1000
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    ports:
      - "8081:80"
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: pma
#    links:
#      - db
#    environment:
#      PMA_HOST: db
#      PMA_PORT: 3306
#      PMA_ARBITRARY: 1
#    ports:
#      - "8081:80"
#    networks:
#      - backend-network
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./php:/php
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - backend-network
  php:
    image: payano/php-fpm-mysql
    container_name: php
    volumes:
        - ./php:/php
    networks:
      - backend-network
  react:
    image: "node:16"
    user: "node"
    container_name: react
    working_dir: /home/node/app
    volumes:
      - ./react-frontend:/home/node/app
    ports:
      - "3000:3000"
    networks:
      - backend-network
    links:
      - web
      - php
    command: "npm start"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001    
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
